# The project's GitHub repository, branches, environments and protection.
#
# A thin root module: the logic lives in Loftline's infra/github-project and
# is referenced here by source, never copied. Fixes to the module reach every
# project on its next `terraform init -upgrade`.
#
#   $env:GITHUB_TOKEN = gh auth token     # PowerShell; bash: export GITHUB_TOKEN=$(gh auth token)
#   cd infra
#   terraform init
#   terraform apply
#
# Then, once, from the project root, commit the generated code on top of the
# initial commit Terraform made. On top of it, not over it: staging and prod
# hold that commit, and a pull request needs a commit in common.
#
#   git init -b dev
#   git remote add origin <clone_url from the apply output>
#   git fetch origin
#   git reset --soft origin/dev
#   git add -A && git commit -m "Generated by Loftline"
#   git push origin dev
#
# staging and prod are reached by pull request from then on.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }

  # State is local until backend.tf exists. See backend.tf.example for the
  # Cloudflare R2 backend, and ADR-018 in Loftline for why local is acceptable
  # for this state and not for others.
}

provider "github" {
  # Token from GITHUB_TOKEN. Under an organisation, add `owner = "org-name"`.
}

module "github" {
  source = "git::https://github.com/CW00D/Loftline.git//infra/github-project?ref=main"

  repository      = var.repository
  description     = var.description
  environments    = var.environments
  required_checks = var.required_checks
  collaborators   = var.collaborators
}

output "repository" {
  value = module.github.repository
}

output "clone_url" {
  value = module.github.clone_url
}

output "environments" {
  value = module.github.environments
}
