import { Link } from "react-router-dom";

import { useAuth } from "@/contexts/useAuth.js";

// The public landing page. Deliberately nothing here: the product starts on
// this page. It proves the site is up and gives a visitor the two doors.
function Home() {
  const { isAuthenticated } = useAuth();

  return (
    <main className="hero">
      <div className="hero__inner">
        <h1 className="hero__title">{document.title}</h1>
        <p className="hero__subtitle">Generated by Loftline. Replace this page.</p>
        <nav className="hero__actions">
          {isAuthenticated ? (
            <Link to="/app" className="button">Your account</Link>
          ) : (
            <>
              <Link to="/login" className="button">Log in</Link>
              <Link to="/signup" className="button button--ghost">Sign up</Link>
            </>
          )}
        </nav>
      </div>
    </main>
  );
}

export default Home;
